# Generated by Django 3.0.5 on 2020-04-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rick_and_morty_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='images',
            field=models.FileField(upload_to='images/'),
        ),
    ]
