# Generated by Django 3.0.5 on 2020-04-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rick_and_morty_app', '0002_auto_20200408_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='lastEpisode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
